[package]
name = "launcher-normalizer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bzip2.workspace = true
flate2.workspace = true
sevenz-rust.workspace = true
tar.workspace = true
unrar.workspace = true
uuid.workspace = true
zip.workspace = true

[lib]
name = "launcher_normalizer"
path = "src/lib.rs"
