<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><AssemblyName>Launcher.Downloads.Tests</AssemblyName></PropertyGroup>
  <ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" /><ProjectReference Include="..\..\src\Launcher.Downloads\Launcher.Downloads.csproj" /><Using Include="Xunit" /></ItemGroup>
</Project>
