[package]
name = "launcher-manifests"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
blake3.workspace = true
launcher-common = { path = "../common" }
rsa-rand.workspace = true
rsa.workspace = true
rsa-sha2.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lib]
name = "launcher_manifests"
