<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Launcher.Networking</AssemblyName>
    <RootNamespace>Launcher.Networking</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Launcher.Core\Launcher.Core.csproj" />
    <ProjectReference Include="..\Launcher.Manifests\Launcher.Manifests.csproj" />
  </ItemGroup>
</Project>
